const SUPABASE_URL="https://oycmdwxmlhchftlunbem.supabase.co";
const SUPABASE_KEY="sb_publishable_jt7eY4iVp3rrT40D6toWpQ_1NcOO0mU";
const $=id=>document.getElementById(id);
let token=sessionStorage.getItem("normly_workbon_access")||sessionStorage.getItem("normly_access")||"";
let user=JSON.parse(sessionStorage.getItem("normly_workbon_user")||sessionStorage.getItem("normly_user")||"null");
let orgs=[],modules=[],assignments=[],dirty=false;
async function api(path,options={}){const r=await fetch(SUPABASE_URL+path,{...options,headers:{"apikey":SUPABASE_KEY,"Authorization":"Bearer "+token,"Content-Type":"application/json",...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.message||d?.error_description||t||"Verzoek mislukt");return d}
function show(id){$(id).classList.remove("hidden")}function hide(id){$(id).classList.add("hidden")}
function msg(text,ok=false){$("message").textContent=text||"";$("message").className="message "+(text?(ok?"ok":"error"):"")}
async function login(){try{const s=await api("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email:$("email").value.trim(),password:$("password").value})});token=s.access_token;user=s.user;sessionStorage.setItem("normly_workbon_access",token);sessionStorage.setItem("normly_workbon_user",JSON.stringify(user));await boot()}catch(e){$("loginError").textContent=e.message;show("loginError")}}
async function boot(){try{if(!user?.id)throw new Error("Geen geldige sessie.");const admins=await api("/rest/v1/app_beheerder?select=gebruiker_id&gebruiker_id=eq."+encodeURIComponent(user.id));if(!admins?.length)throw new Error("Dit account heeft geen Normly-platformbeheerrechten.");const [o,m,a]=await Promise.all([api("/rest/v1/organisatie?select=id,naam,actieve_modules&order=naam.asc"),api("/rest/v1/normly_module?select=sleutel,naam,omschrijving,actief,volgorde&order=volgorde.asc"),api("/rest/v1/organisatie_module?select=organisatie_id,module_sleutel,actief")]);orgs=o||[];modules=m||[];assignments=a||[];$("adminName").textContent=user.email||"Platformbeheer";render();hide("loginView");show("adminView")}catch(e){token="";sessionStorage.removeItem("normly_workbon_access");$("loginError").textContent=e.message;show("loginError");show("loginView");hide("adminView")}}
function isOn(org,key){const a=assignments.find(x=>x.organisatie_id===org.id&&x.module_sleutel===key);return a?!!a.actief:false}
function render(){const activeCount=orgs.reduce((n,o)=>n+modules.filter(m=>m.actief&&isOn(o,m.sleutel)).length,0);$("orgCount").textContent=orgs.length+" organisaties";$("moduleCount").textContent=modules.filter(m=>m.actief).length+" actieve modules";$("activeCount").textContent=activeCount+" toewijzingen";$("orgList").innerHTML=orgs.map(o=>'<div class="org-row"><div><div class="org-name">'+esc(o.naam)+'</div><div class="org-meta">'+(modules.filter(m=>m.actief&&isOn(o,m.sleutel)).map(m=>esc(m.naam)).join(" · ")||"Geen modules actief")+'</div></div><div class="modules">'+modules.map(m=>{const on=isOn(o,m.sleutel),disabled=!m.actief;return '<label class="module '+(on?"active ":"")+(disabled?"disabled":"")+'"><input type="checkbox" data-org="'+o.id+'" data-module="'+esc(m.sleutel)+'" '+(on?"checked":"")+(disabled?" disabled":"")+'><span class="module-info"><strong>'+esc(m.naam)+(disabled?'<span class="pill">Binnenkort</span>':"")+'</strong><small>'+esc(m.omschrijving||"")+'</small></span></label>'}).join("")+"</div></div>").join("");document.querySelectorAll("[data-org][data-module]").forEach(x=>x.addEventListener("change",()=>{dirty=true;x.closest(".module").classList.toggle("active",x.checked);$("saveText").textContent="Wijzigingen nog niet opgeslagen"}))}
async function save(){try{$("saveButton").disabled=true;msg("Wijzigingen opslaan…");for(const c of [...document.querySelectorAll("[data-org][data-module]")]){const org=c.dataset.org,key=c.dataset.module,on=c.checked;const old=assignments.find(a=>a.organisatie_id===org&&a.module_sleutel===key);const payload={organisatie_id:org,module_sleutel:key,actief:on,ingesteld_door:user.id};if(old)await api("/rest/v1/organisatie_module?organisatie_id=eq."+encodeURIComponent(org)+"&module_sleutel=eq."+encodeURIComponent(key),{method:"PATCH",headers:{"Prefer":"return=minimal"},body:JSON.stringify({actief:on,ingesteld_door:user.id})});else await api("/rest/v1/organisatie_module",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(payload)});assignments=assignments.filter(a=>!(a.organisatie_id===org&&a.module_sleutel===key));assignments.push(payload);const o=orgs.find(x=>x.id===org);let legacy=Array.isArray(o.actieve_modules)?[...o.actieve_modules]:[];const legacyKey=key==="vgm"?"werkplekinspectie":key;legacy=legacy.filter(x=>x!==legacyKey);if(on)legacy.push(legacyKey);await api("/rest/v1/organisatie?id=eq."+encodeURIComponent(org),{method:"PATCH",headers:{"Prefer":"return=minimal"},body:JSON.stringify({actieve_modules:[...new Set(legacy)]})});o.actieve_modules=[...new Set(legacy)]}dirty=false;msg("Moduletoegang is opgeslagen.",true);$("saveText").textContent="Alle wijzigingen zijn opgeslagen";render()}catch(e){msg(e.message||"Opslaan mislukt.")}finally{$("saveButton").disabled=false}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("loginButton").addEventListener("click",login);$("password").addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("saveButton").addEventListener("click",save);$("logout").addEventListener("click",()=>{sessionStorage.removeItem("normly_workbon_access");sessionStorage.removeItem("normly_workbon_user");location.reload()});if(token&&user)boot();else show("loginView");
